### ISSUE TITLE
Criar role para o nomad

### ISSUE THREAD

**Issue by afonsoaugusto** [mentoriaiac/iac_role_nomad#1]
Criar role para o nomad

**Comment by gomex** [comment]
O ideal que essa role tenha ao menos:

Uma role seguindo os padrões do molecule.
Algum teste automatizado de infra
CI/CD rodando o molecule test

**Comment by gomex** [comment]
O PR #2 fez praticamente tudo, mas ainda está pendente a criação do script que será executado pra criação do cluster.

**Comment by cflb** [comment]
Proposta inicial dos requisitos, por @gomex:
- O script precisa sair com exit code 0 quando concluir todos os passos com sucesso, mas sair com exit 1 caso quebre algo.
- A localização do script precisa seguir o FHS: https://pt.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
- O script precisa ser executável
- O script não deve ter nenhum valor hardcode, tudo precisa ser passado na chamada ou via variável de ambiente
- Seria bem legal se ele pudesse jogar sua saída de mensagem para um arquivo de log (/var/log/nomad_cluster.log ?)

**Comment by afonsoaugusto** [comment]
> Proposta inicial dos requisitos, por @gomex:
> 
> * O script precisa sair com exit code 0 quando concluir todos os passos com sucesso, mas sair com exit 1 caso quebre algo.
> * A localização do script precisa seguir o FHS: https://pt.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
> * O script precisa ser executável
> * O script não deve ter nenhum valor hardcode, tudo precisa ser passado na chamada ou via variável de ambiente
> * Seria bem legal se ele pudesse jogar sua saída de mensagem para um arquivo de log (/var/log/nomad_cluster.log ?)

opa @cflb , o PR #2 já resolve todos estes pontos?
Se não, acho que seria legal fecharmos essa issue e abrir novas issues para os pontos não atendidos.

**Comment by cflb** [comment]
@afonsoaugusto ainda não, o segundo PR tem relação apenas com o plugin CNI. Mas esta semana podemos fechar esta issue, posso trabalhar nela na quinta-feira (26/08/2021)

**Comment by afonsoaugusto** [comment]
@cflb entendi...
Tranquilo :smile:

**Comment by gomex** [comment]
O PR #6 conclui com essa issue.
