### ISSUE TITLE
Habilitar ACL

### ISSUE THREAD

**Issue by lgfa29** [mentoriaiac/iac_role_nomad#10]
Para ambientes de produção é necessário habilitar controle de acesso (ACL).

### Referências
- https://learn.hashicorp.com/tutorials/nomad/access-control-bootstrap?in=nomad/access-control#enable-acls-on-nomad-servers
- https://learn.hashicorp.com/tutorials/nomad/access-control-bootstrap?in=nomad/access-control#enable-acls-on-nomad-clients

**Comment by gomex** [comment]
Resolvido pelo PR #13
